# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transducer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smok_Transducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('smoke', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoke', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner', 'smoke', 'time'),
            },
        ),
    ]
